version: '3.8'

services:
  artemis:
    container_name: artemis_container
    image: palomi/artemis-amq-amd64:2.32.0-SNAPSHOT #amd64
    # image: palomi/artemis-amq-arm64:2.18.0-SNAPSHOT #arm64
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      AMQ_USER: artemis
      AMQ_PASSWORD: artemis
      ARTEMIS_USER: artemis
      ARTEMIS_PASSWORD: artemis
      ANONYMOUS_LOGIN: false
      EXTRA_ARGS: --http-host 0.0.0.0 --relax-jolokia